# Generated by Django 4.0.5 on 2022-06-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('clientTech', models.CharField(max_length=50)),
                ('serverTech', models.CharField(max_length=50)),
                ('databaseTech', models.CharField(max_length=50)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
