# Generated by Django 4.0.5 on 2022-06-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clientTech',
        ),
        migrations.RemoveField(
            model_name='project',
            name='databaseTech',
        ),
        migrations.RemoveField(
            model_name='project',
            name='serverTech',
        ),
    ]
